#!/usr/bin/env python3

"""
batch_migrate_to_github.py

Automates the pushing of git mirrors and migration of metadata 
from a local GitLab archive directory to a target GitHub organization.

Usage:
  python batch_migrate_to_github.py \
    --archive-dir ./gitlab_archives \
    --github-org my-github-org
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

def run_command(cmd, cwd=None):
    """Helper to run a command and stream the output."""
    print(f"  > {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if result.returncode != 0:
        print(f"  [!] Command failed:\n{result.stdout}")
        return False
    return True

def main():
    parser = argparse.ArgumentParser(description="Batch migrate archived GitLab repos to GitHub.")
    parser.add_argument("--archive-dir", required=True, help="Path to the directory containing index.json and unzipped archives.")
    parser.add_argument("--github-org", required=True, help="Target GitHub organization or username (e.g., billingegroup).")
    parser.add_argument("--metadata-script", default="gitlab_metadata_to_github.py", help="Path to your metadata migration script.")
    args = parser.parse_args()

    archive_dir = Path(args.archive_dir)
    index_path = archive_dir / "index.json"

    if not index_path.exists():
        print(f"Error: Could not find {index_path}. Are you pointing to the correct archive directory?")
        sys.exit(1)

    # Load the master index
    with open(index_path, "r", encoding="utf-8") as f:
        master_index = json.load(f)

    results = master_index.get("results", [])
    if not results:
        print("No archived projects found in index.json.")
        sys.exit(0)

    print(f"Found {len(results)} projects in index. Starting batch migration to GitHub org: '{args.github_org}'\n")

    for proj in results:
        if proj.get("status") != "done":
            print(f"Skipping '{proj.get('path')}' because its archive status was: {proj.get('status')}")
            continue

        proj_id = proj["id"]
        path_with_ns = proj["path"]
        
        # Reconstruct the folder names as generated by the archive script
        safe_name = path_with_ns.replace("/", "__")
        project_dir = archive_dir / f"{safe_name}-{proj_id}"
        
        # The base name of the repository (e.g., 'myrepo' from 'billingegroup/myrepo')
        repo_name = path_with_ns.split("/")[-1]
        
        # Expected paths
        git_dir = project_dir / f"{repo_name}.git"
        metadata_file = project_dir / "metadata.json"

        target_github_repo = f"{args.github_org}/{repo_name}"
        target_github_url = f"https://github.com/{target_github_repo}.git"

        print(f"--- Processing: {repo_name} ---")

        if not project_dir.exists():
            print(f"  [!] Directory {project_dir} not found. Did you unzip the archives?")
            print("-" * 40)
            continue

        # Step 1: Push the bare mirror to GitHub
        if git_dir.exists():
            print(f"  Pushing Git history to {target_github_url} ...")
            push_success = run_command(["git", "push", "--mirror", target_github_url], cwd=str(git_dir))
            
            if not push_success:
                print("  [!] Git push failed. Skipping metadata migration for this repo to avoid orphan data.")
                print("-" * 40)
                continue
        else:
            print(f"  [!] Bare git directory not found at {git_dir}. Skipping.")
            print("-" * 40)
            continue

        # Step 2: Run the metadata migration script
        if metadata_file.exists():
            print(f"  Migrating metadata (Issues, PRs, Labels) ...")
            run_command([
                sys.executable, args.metadata_script,
                "--metadata", str(metadata_file),
                "--github-repo", target_github_repo
            ])
        else:
            print(f"  [!] No metadata.json found at {metadata_file}. Skipping metadata migration.")

        print(f"  Done with {repo_name}.\n" + "-" * 40 + "\n")

if __name__ == "__main__":
    main()
